steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME",
        "."
      ]
  # Push the image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME"]
  # Manual Deploy image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "$REPO_NAME-$BRANCH_NAME",
        "--image",
        "$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME",
        "--region",
        "$LOCATION",
        "--platform",
        "managed",
        "--port",
        "80",
        "--max-instances",
        "30",
        "--update-env-vars=API_PORT=80",
        "--allow-unauthenticated"
      ]
images:
  - "$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME"
