version: "3"

services:
  app:
    container_name: next-base-skeleton
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:80"
    environment:
      NODE_ENV: development
